services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: "rabbitmq"
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq_docker_network
    restart: always
  codefest:
    container_name: "codefest"
    image: leonardocbsr/codefest:latest
    depends_on:
      - rabbitmq
    restart: always
    networks:
      - rabbitmq_docker_network

networks:
  rabbitmq_docker_network:
    driver: bridge